In [119]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
plt.switch_backend('TkAgg')
plt.rc('font', family='Malgun Gothic')
plt.rc('axes', unicode_minus=False)

In [120]:
#선형회귀(최소제곱법)
from sklearn.linear_model import LinearRegression

In [121]:
dataset = pd.read_csv('data/LinearRegressionData.csv')
dataset.head()

hour  score
0   0.5     10
1   1.2      8
2   1.8     14
3   2.4     26
4   2.6     22

In [122]:
#독립변수
X = dataset.iloc[:, :-1].values
X.shape

(22, 1)

In [123]:
#종속변수
y = dataset.iloc[:, -1].values
y.shape

(22,)

In [ ]:
reg = LinearRegression()
reg.fit(X, y)

LinearRegression()

In [125]:
#9시간 공부했을 때 점수
pred = reg.predict([[9]])
pred[0], pred.shape

(np.float64(87.50951711379335), (1,))

In [126]:
#8, 7, 5시간 공부했을 때 점수?
pred = reg.predict([[8], [7], [5]])
print(pred[0], pred[1], pred[2], pred.shape)

79.56490004438926 71.62028297498517 55.731048836176996 (3,)


In [127]:
import math
import numpy as np
max =math.ceil(X.max())
xticks = [x for x in np.arange(0, max+1, 0.5)]
print(xticks)


[np.float64(0.0), np.float64(0.5), np.float64(1.0), np.float64(1.5), np.float64(2.0), np.float64(2.5), np.float64(3.0), np.float64(3.5), np.float64(4.0), np.float64(4.5), np.float64(5.0), np.float64(5.5), np.float64(6.0), np.float64(6.5), np.float64(7.0), np.float64(7.5), np.float64(8.0), np.float64(8.5), np.float64(9.0), np.float64(9.5), np.float64(10.0), np.float64(10.5), np.float64(11.0), np.float64(11.5)]


In [128]:
#실제점수와 예측점수를 시각화
plt.figure(figsize=(10,5))
plt.scatter(X, y, label='실제점수')
plt.plot(X, reg.predict(X), color='g', label='예측점수')
plt.grid(True, ls='--', lw=0.5)
plt.xticks(xticks, [f'{x}h' for x in xticks], size=8, rotation=45)
plt.legend(loc='lower right')
plt.show()


In [129]:
#y=mx+b
m = reg.coef_
b = reg.intercept_
y1 = m*9 + b
y1

array([87.50951711])

In [130]:
reg.predict([[9]])

array([87.50951711])

In [131]:
#선형회귀(경사하강법)
from sklearn.linear_model import SGDRegressor

In [132]:
X.shape, y.shape

((22, 1), (22,))

In [133]:
sr = SGDRegressor()
sr.fit(X, y)

SGDRegressor()

In [134]:
#9시간 공부했을 때 점수?
sr.predict([[9]]), reg.predict([[9]])

(array([91.5663286]), array([87.50951711]))

In [135]:
plt.figure(figsize=(10,5))
plt.scatter(X, y)
plt.plot(X, sr.predict(X), color='g')
plt.show()

In [136]:
sr.score(X, y), reg.score(X, y)

(0.5610251979681755, 0.5896028693137483)

In [137]:
sr.coef_, reg.coef_, sr.intercept_, reg.intercept_

(array([9.51806411]),
 array([7.94461707]),
 array([5.90375163]),
 np.float64(16.007963489156545))

In [138]:
sr = SGDRegressor(max_iter=4300, eta0=0.0001, random_state=0, verbose=1)
sr.fit(X, y)

-- Epoch 1
Norm: 0.42, NNZs: 1, Bias: 0.068941, T: 22, Avg. loss: 1923.504719
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.72, NNZs: 1, Bias: 0.117862, T: 44, Avg. loss: 1804.001484
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.98, NNZs: 1, Bias: 0.159928, T: 66, Avg. loss: 1712.422791
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 1.21, NNZs: 1, Bias: 0.197451, T: 88, Avg. loss: 1633.991026
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 1.42, NNZs: 1, Bias: 0.231958, T: 110, Avg. loss: 1564.879431
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 1.61, NNZs: 1, Bias: 0.264029, T: 132, Avg. loss: 1502.274723
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 1.80, NNZs: 1, Bias: 0.294202, T: 154, Avg. loss: 1445.211057
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 1.97, NNZs: 1, Bias: 0.322722, T: 176, Avg. loss: 1392.617425
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 2.14, NNZs: 1, Bias: 0.349850, T: 198, Avg. loss: 1344.011991
Total trainin

SGDRegressor(eta0=0.0001, max_iter=4300, random_state=0, verbose=1)

In [139]:
plt.figure(figsize=(10,5))
plt.scatter(X, y)
plt.plot(X, sr.predict(X), color='g')
plt.show()

In [140]:
import warnings
warnings.filterwarnings('ignore')

In [141]:
def model_sgd(iter, eta0):
    sr = SGDRegressor(max_iter=iter, eta0=eta0, random_state=0)
    sr.fit(X, y)

In [142]:
for i in range(100, 1001, 500):
    model_sgd(i, 10e-3)
    plt.figure(figsize=(10,5))
    plt.scatter(X, y)
    plt.plot(X, sr.predict(X), color='g')
    plt.title(f'iter={i}', size=20)
    plt.show(block=False)
    plt.pause(2)
    plt.close()

In [143]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [144]:
X_train.shape, X_test.shape, X.shape

((17, 1), (5, 1), (22, 1))

In [145]:
sr = SGDRegressor()
sr.fit(X_train, y_train)

SGDRegressor()

In [146]:
sr.predict(X_test), X_test

(array([100.75874986,  57.35523808,  64.86738435,  64.03270143,
         23.13323841]),
 array([[10.5],
        [ 5.3],
        [ 6.2],
        [ 6.1],
        [ 1.2]]))